{% set version = "24.2.3" %}
{% set sha256 = "c1204ff484d37fedc9f0c52234405d466d064f0bafef76d1eadd19f503f8415b" %}

package:
  name: galaxy-util
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/galaxy-util/galaxy_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bleach
    - boltons
    - docutils
    - importlib_resources
    - packaging
    - pyparsing
    - python >={{ python_min }}
    - pyyaml
    - requests
    - routes
    - typing_extensions
    - zipstream-new
    # extras_require:
    #- dictobj
    - future >=1.0.0
    - cheetah3
  run_constrained:
    # Disallow installation of conflicting older package.
    - galaxy-lib <0a0

test:
  requires:
    - python {{ python_min }}
  imports:
    - galaxy
    - galaxy.exceptions
    - galaxy.util
    - galaxy.util.custom_logging
    - galaxy.util.path
    - galaxy.util.tool_shed

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: Galaxy Generic Utilities
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
